/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    KanbanBoard: typeof import('./src/components/KanbanBoard.vue')['default']
    KanbanBord: typeof import('./src/components/KanbanBord.vue')['default']
    KanbanCard: typeof import('./src/components/KanbanCard.vue')['default']
    KanbanColumn: typeof import('./src/components/KanbanColumn.vue')['default']
  }
}
